# Generated by Django 3.2.9 on 2021-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
