# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211130_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_nivel',
            new_name='nivel',
        ),
    ]
