# Generated by Django 3.2.9 on 2021-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20211202_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
