# Generated by Django 3.2.9 on 2021-11-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_id_nivel_usuario_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel',
            old_name='codigo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='codigo',
            new_name='id',
        ),
    ]
