# Generated by Django 3.2.9 on 2021-11-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20211130_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='confiabilidad',
        ),
    ]
