# Generated by Django 3.2.9 on 2021-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_comentario_confiabilidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calificaciones',
            new_name='Calificacion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='contenido',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='enunciado',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='contenido',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
